export const products = [
  {
    id: 1,
    title: "Essential Oversized Hoodie",
    brand: "Nike",
    slug: "nike-essential-oversized-hoodie",
    price: 34.99,
    rating: 4.8,
    reviews: 421,
    category: "Hoodies",
    description: "Soft cotton oversized hoodie designed for everyday comfort.",
    image: "/images/products/white_hoodie.jpg",
    stock: 25,
    featured: true,
  },
  {
    id: 2,
    title: "Club Fleece Hoodie",
    brand: "Nike",
    slug: "nike-club-fleece-hoodie",
    price: 64.99,
    rating: 4.9,
    reviews: 315,
    category: "Hoodies",
    description: "Classic fleece hoodie with brushed interior for warmth.",
    image: "/images/products/grey_hoodie.jpg",
    stock: 18,
    featured: true,
  },
  {
    id: 3,
    title: "Trefoil Hoodie",
    brand: "Adidas",
    slug: "adidas-trefoil-hoodie",
    price: 69.99,
    rating: 4.8,
    reviews: 258,
    category: "Hoodies",
    description: "Iconic Trefoil hoodie made from a soft cotton blend.",
    image: "/images/products/sport_grey_hoodie.jpg",
    stock: 15,
    featured: true,
  },
  {
    id: 4,
    title: "Sportswear Hoodie",
    brand: "Nike",
    slug: "nike-sportswear-hoodie",
    price: 54.99,
    rating: 4.7,
    reviews: 194,
    category: "Hoodies",
    description: "Comfortable everyday hoodie with a relaxed athletic fit.",
    image: "/images/products/blue_hoodie.jpg",
    stock: 20,
    featured: false,
  },
  {
    id: 5,
    title: "Essentials Logo Hoodie",
    brand: "Puma",
    slug: "puma-essentials-logo-hoodie",
    price: 29.99,
    rating: 4.6,
    reviews: 172,
    category: "Hoodies",
    description: "Minimal logo hoodie crafted from soft fleece fabric.",
    image: "/images/products/navy_hoodie.jpg",
    stock: 30,
    featured: false,
  },
  {
    id: 6,
    title: "Tech Fleece Hoodie",
    brand: "Nike",
    slug: "nike-tech-fleece-hoodie",
    price: 159.99,
    rating: 4.9,
    reviews: 584,
    category: "Hoodies",
    description: "Premium Tech Fleece hoodie offering warmth without bulk.",
    image: "/images/products/purple_hoodie.jpg",
    stock: 10,
    featured: true,
  },
  {
    id: 7,
    title: "Essentials Hoodie",
    brand: "Adidas",
    slug: "adidas-essentials-hoodie",
    price: 109.99,
    rating: 4.8,
    reviews: 447,
    category: "Hoodies",
    description: "Classic Adidas hoodie with a timeless sporty design.",
    image: "/images/products/violet_hoodie.jpg",
    stock: 12,
    featured: true,
  },
  {
    id: 8,
    title: "Classic Hoodie",
    brand: "Converse",
    slug: "converse-classic-hoodie",
    price: 74.99,
    rating: 4.8,
    reviews: 637,
    category: "Hoodies",
    description: "Classic Converse hoodie perfect for everyday casual wear.",
    image: "/images/products/red_hoodie.jpg",
    stock: 22,
    featured: false,
  },
  {
    id: 9,
    title: "Denim Blue Hoodie",
    brand: "Levi's",
    slug: "levis-denim-blue-hoodie",
    price: 99.99,
    rating: 4.7,
    reviews: 181,
    category: "Hoodies",
    description: "Premium cotton hoodie inspired by Levi's classic denim style.",
    image: "/images/products/pink_hoodie.jpg",
    stock: 1,
    featured: false,
  },
  {
    id: 10,
    title: "Insulated Hoodie",
    brand: "The North Face",
    slug: "the-north-face-insulated-hoodie",
    price: 249.99,
    rating: 4.9,
    reviews: 212,
    category: "Hoodies",
    description: "Warm insulated hoodie designed for cold-weather comfort.",
    image: "/images/products/maroon_hoodie.jpg",
    stock: 0,
    featured: true,
  },
  {
    id: 11,
    title: "Slim Fit Hoodie",
    brand: "Levi's",
    slug: "levis-slim-fit-hoodie",
    price: 79.99,
    rating: 4.7,
    reviews: 296,
    category: "Hoodies",
    description: "Modern slim-fit hoodie with soft brushed fleece lining.",
    image: "/images/products/orange_hoodie.jpg",
    stock: 17,
    featured: false,
  },
  {
    id: 12,
    title: "Utility Hoodie",
    brand: "Carhartt WIP",
    slug: "carhartt-utility-hoodie",
    price: 89.99,
    rating: 4.8,
    reviews: 154,
    category: "Hoodies",
    description: "Heavyweight hoodie built for durability and comfort.",
    image: "/images/products/gold_hoodie.jpg",
    stock: 14,
    featured: false,
  },
  {
    id: 13,
    title: "Quarter Zip Hoodie",
    brand: "Tommy Hilfiger",
    slug: "tommy-quarter-zip-hoodie",
    price: 94.99,
    rating: 4.6,
    reviews: 121,
    category: "Hoodies",
    description: "Soft quarter-zip hoodie featuring Tommy Hilfiger branding.",
    image: "/images/products/gold_hoodie.jpg",
    stock: 13,
    featured: false,
  },
  {
    id: 14,
    title: "Graphic Hoodie",
    brand: "Calvin Klein",
    slug: "calvin-klein-graphic-hoodie",
    price: 39.99,
    rating: 4.7,
    reviews: 138,
    category: "Hoodies",
    description: "Minimalist graphic hoodie made from premium cotton fleece.",
    image: "/images/products/sapphire_hoodie.jpg",
    stock: 26,
    featured: false,
  },
  {
    id: 15,
    title: "Performance Hoodie",
    brand: "Under Armour",
    slug: "under-armour-performance-hoodie",
    price: 44.99,
    rating: 4.8,
    reviews: 169,
    category: "Hoodies",
    description: "Performance hoodie with moisture-wicking technology.",
    image: "/images/products/yellow_hoodie.jpg",
    stock: 21,
    featured: false,
  },
  {
    id: 16,
    title: "Relaxed Fit Hoodie",
    brand: "H&M",
    slug: "hm-relaxed-fit-hoodie",
    price: 39.99,
    rating: 4.5,
    reviews: 201,
    category: "Hoodies",
    description: "Relaxed everyday hoodie with soft brushed interior.",
    image: "/images/products/green_hoodie.jpg",
    stock: 24,
    featured: false,
  },
  {
    id: 17,
    title: "Court Style Hoodie",
    brand: "Nike",
    slug: "nike-court-style-hoodie",
    price: 89.99,
    rating: 4.7,
    reviews: 273,
    category: "Hoodies",
    description: "Court-inspired hoodie combining comfort with modern style.",
    image: "/images/products/chocolate_hoodie.jpg",
    stock: 16,
    featured: false,
  },
  {
    id: 18,
    title: "Essentials Fleece Hoodie",
    brand: "Adidas",
    slug: "adidas-essentials-fleece-hoodie",
    price: 59.99,
    rating: 4.6,
    reviews: 186,
    category: "Hoodies",
    description: "Comfortable fleece hoodie ideal for everyday wear.",
    image: "/images/products/garnet_hoodie.jpg",
    stock: 19,
    featured: false,
  },
  {
    id: 19,
    title: "Windproof Hoodie",
    brand: "Columbia",
    slug: "columbia-windproof-hoodie",
    price: 119.99,
    rating: 4.8,
    reviews: 144,
    category: "Hoodies",
    description: "Lightweight wind-resistant hoodie for outdoor adventures.",
    image: "/images/products/light_blue_hoodie.jpg",
    stock: 0,
    featured: false,
  },
  {
    id: 20,
    title: "574 Heritage Hoodie",
    brand: "New Balance",
    slug: "new-balance-574-heritage-hoodie",
    price: 109.99,
    rating: 4.9,
    reviews: 502,
    category: "Hoodies",
    description: "Premium heavyweight hoodie inspired by the iconic 574 collection.",
    image: "/images/products/beige_hoodie.jpg",
    stock: 14,
    featured: true,
  },
];
