export const products = [
  {
    id: 1,
    title: "Essential Oversized Hoodie",
    brand: "Nike",
    slug: "nike-essential-oversized-hoodie",
    price: 34.99,
    rating: 4.8,
    reviews: 421,
    category: "Hoodies",
    description: "Soft cotton oversized hoodie designed for everyday comfort.",
    images: [
      "/images/products/product_images_lg/white_hoodie.jpg",
      "/images/products/product_images_sm/white_hoodie_2.jpg",
    ],
    stock: 25,
    featured: true,
  },
  {
    id: 2,
    title: "Club Fleece Hoodie",
    brand: "Nike",
    slug: "nike-club-fleece-hoodie",
    price: 64.99,
    rating: 4.9,
    reviews: 315,
    category: "Hoodies",
    description: "Classic fleece hoodie with brushed interior for warmth.",
    images: [
      "/images/products/product_images_lg/grey_hoodie.jpg",
      "/images/products/product_images_sm/grey_hoodie_2.jpg",
    ],
    stock: 18,
    featured: true,
  },
  {
    id: 3,
    title: "Trefoil Hoodie",
    brand: "Adidas",
    slug: "adidas-trefoil-hoodie",
    price: 69.99,
    rating: 4.8,
    reviews: 258,
    category: "Hoodies",
    description: "Iconic Trefoil hoodie made from a soft cotton blend.",
    images: [
      "/images/products/product_images_lg/sport_grey_hoodie.jpg",
      "/images/products/product_images_sm/sport_grey_hoodie_2.jpg",
    ],
    stock: 15,
    featured: true,
  },
  {
    id: 4,
    title: "Sportswear Hoodie",
    brand: "Nike",
    slug: "nike-sportswear-hoodie",
    price: 54.99,
    rating: 4.7,
    reviews: 194,
    category: "Hoodies",
    description: "Comfortable everyday hoodie with a relaxed athletic fit.",
    images: [
      "/images/products/product_images_lg/blue_hoodie.jpg",
      "/images/products/product_images_sm/blue_hoodie_2.jpg",
    ],
    stock: 20,
    featured: false,
  },
  {
    id: 5,
    title: "Essentials Logo Hoodie",
    brand: "Puma",
    slug: "puma-essentials-logo-hoodie",
    price: 29.99,
    rating: 4.6,
    reviews: 172,
    category: "Hoodies",
    description: "Minimal logo hoodie crafted from soft fleece fabric.",
    images: [
      "/images/products/product_images_lg/navy_hoodie.jpg",
      "/images/products/product_images_sm/navy_hoodie_2.jpg",
    ],
    stock: 30,
    featured: false,
  },
  {
    id: 6,
    title: "Tech Fleece Hoodie",
    brand: "Nike",
    slug: "nike-tech-fleece-hoodie",
    price: 159.99,
    rating: 4.9,
    reviews: 584,
    category: "Hoodies",
    description: "Premium Tech Fleece hoodie offering warmth without bulk.",
    images: [
      "/images/products/product_images_lg/purple_hoodie.jpg",
      "/images/products/product_images_sm/purple_hoodie_2.jpg",
    ],
    stock: 10,
    featured: true,
  },
  {
    id: 7,
    title: "Essentials Hoodie",
    brand: "Adidas",
    slug: "adidas-essentials-hoodie",
    price: 109.99,
    rating: 4.8,
    reviews: 447,
    category: "Hoodies",
    description: "Classic Adidas hoodie with a timeless sporty design.",
    images: [
      "/images/products/product_images_lg/violet_hoodie.jpg",
      "/images/products/product_images_sm/violet_hoodie_2.jpg",
    ],
    stock: 12,
    featured: true,
  },
  {
    id: 8,
    title: "Classic Hoodie",
    brand: "Converse",
    slug: "converse-classic-hoodie",
    price: 74.99,
    rating: 4.8,
    reviews: 637,
    category: "Hoodies",
    description: "Classic Converse hoodie perfect for everyday casual wear.",
    images: [
      "/images/products/product_images_lg/red_hoodie.jpg",
      "/images/products/product_images_sm/red_hoodie_2.jpg",
    ],
    stock: 22,
    featured: false,
  },
  {
    id: 9,
    title: "Denim Blue Hoodie",
    brand: "Levi's",
    slug: "levis-denim-blue-hoodie",
    price: 99.99,
    rating: 4.7,
    reviews: 181,
    category: "Hoodies",
    description: "Premium cotton hoodie inspired by Levi's classic denim style.",
    images: [
      "/images/products/product_images_lg/pink_hoodie.jpg",
      "/images/products/product_images_sm/pink_hoodie_2.jpg",
    ],
    stock: 1,
    featured: false,
  },
  {
    id: 10,
    title: "Insulated Hoodie",
    brand: "The North Face",
    slug: "the-north-face-insulated-hoodie",
    price: 249.99,
    rating: 4.9,
    reviews: 212,
    category: "Hoodies",
    description: "Warm insulated hoodie designed for cold-weather comfort.",
    images: [
      "/images/products/product_images_lg/maroon_hoodie.jpg",
      "/images/products/product_images_sm/maroon_hoodie_2.jpg",
    ],
    stock: 0,
    featured: true,
  },
];
